FROM bchunlimited/pyrrha:ubuntu20.04

# change the url to your forked repo if you dont want to pull the bitcoinunlimted repo
RUN git clone https://gitlab.com/pyrrha/pyrrha

# to checkout a specific branch uncomment the lines in the section below
###############
# WORKDIR /pyrrha
# git checkout <branch name>
###############


WORKDIR /pyrrha

RUN ./autogen.sh
RUN ./configure --disable-dependency-tracking --enable-glibc-back-compat --enable-reduce-exports LDFLAGS=-static-libstdc++ --with-gui=no --with-incompatible-bdb

RUN make -j`nproc`

RUN mkdir /root/.pyrrha/
