

#include <QtGlobal>

// Automatically generated by extract_strings.py
#ifdef __GNUC__
#define UNUSED __attribute__((unused))
#else
#define UNUSED
#endif
static const char UNUSED *bitcoin_strings[] = {
    QT_TRANSLATE_NOOP("pyrrha", "Pyrrha"),
    QT_TRANSLATE_NOOP("pyrrha", "The %s developers"),
    QT_TRANSLATE_NOOP("pyrrha", "Bitcoin Bitcoin XT and Bitcoin Unlimited"),
    QT_TRANSLATE_NOOP("pyrrha",
        ""
        "-wallet.maxTxFee is set very high! Fees this large could be paid on a single "
        "transaction."),
    QT_TRANSLATE_NOOP("pyrrha",
        ""
        "-wallet.payTxFee is set very high! This is the transaction fee you will pay "
        "if you send a transaction."),
    QT_TRANSLATE_NOOP("pyrrha",
        ""
        "Cannot obtain a lock on data directory %s. %s is probably already running."),
    QT_TRANSLATE_NOOP("pyrrha",
        ""
        "Could not locate RPC credentials. No authentication cookie could be found, "
        "and no rpcpassword is set in the configuration file (%s)"),
    QT_TRANSLATE_NOOP("pyrrha",
        ""
        "Deployment configuration file '%s' contained invalid data - see debug.log"),
    QT_TRANSLATE_NOOP("pyrrha",
        ""
        "Distributed under the MIT software license, see the accompanying file "
        "COPYING or <http://www.opensource.org/licenses/mit-license.php>."),
    QT_TRANSLATE_NOOP("pyrrha",
        ""
        "Error loading %s: You can't enable HD on a already existing non-HD wallet"),
    QT_TRANSLATE_NOOP("pyrrha",
        ""
        "Error reading %s! All keys read correctly, but transaction data or address "
        "book entries might be missing or incorrect."),
    QT_TRANSLATE_NOOP("pyrrha",
        ""
        "Error reading from the coin database.\n"
        "Details: %s\n"
        "\n"
        "Do you want to reindex on the next restart?"),
    QT_TRANSLATE_NOOP("pyrrha",
        ""
        "Error: Listening for incoming connections failed (listen returned error %s)"),
    QT_TRANSLATE_NOOP("pyrrha",
        ""
        "Failed to listen on all P2P ports. Failing as requested by -bindallorfail."),
    QT_TRANSLATE_NOOP("pyrrha",
        ""
        "Fee: %ld is larger than configured maximum allowed fee of : %ld.  To change, "
        "set 'wallet.maxTxFee'."),
    QT_TRANSLATE_NOOP("pyrrha",
        ""
        "Invalid amount for -wallet.maxTxFee=<amount>: '%u' (must be at least the "
        "minrelay fee of %s to prevent stuck transactions)"),
    QT_TRANSLATE_NOOP("pyrrha",
        ""
        "Invalid amount for -wallet.payTxFee=<amount>: '%u' (must be at least %s)"),
    QT_TRANSLATE_NOOP("pyrrha",
        ""
        "Please check that your computer's date and time are correct! If your clock "
        "is wrong, %s will not work properly."),
    QT_TRANSLATE_NOOP("pyrrha",
        ""
        "Prune configured below the minimum of %d MiB.  Please use a higher number."),
    QT_TRANSLATE_NOOP("pyrrha",
        ""
        "Prune: last wallet synchronisation goes beyond pruned data. You need to -"
        "reindex (download the whole blockchain again in case of pruned node)"),
    QT_TRANSLATE_NOOP("pyrrha",
        ""
        "Reducing -maxconnections from %d to %d because of file descriptor "
        "limitations (unix) or winsocket fd_set limitations (windows). If you are a "
        "windows user there is a hard upper limit of 1024 which cannot be changed by "
        "adjusting the node's configuration."),
    QT_TRANSLATE_NOOP("pyrrha",
        ""
        "Rescans are not possible in pruned mode. You will need to use -reindex which "
        "will download the whole blockchain again."),
    QT_TRANSLATE_NOOP("pyrrha",
        ""
        "The block database contains a block which appears to be from the future. "
        "This may be due to your computer's date and time being set incorrectly. Only "
        "rebuild the block database if you are sure that your computer's date and "
        "time are correct"),
    QT_TRANSLATE_NOOP("pyrrha",
        ""
        "The transaction amount is too small to send after the fee has been deducted"),
    QT_TRANSLATE_NOOP("pyrrha",
        ""
        "This is a pre-release test build - use at your own risk - do not use for "
        "mining or merchant applications"),
    QT_TRANSLATE_NOOP("pyrrha",
        ""
        "This product includes software developed by the OpenSSL Project for use in "
        "the OpenSSL Toolkit <https://www.openssl.org/> and cryptographic software "
        "written by Eric Young and UPnP software written by Thomas Bernard."),
    QT_TRANSLATE_NOOP("pyrrha",
        ""
        "Total length of network version string with uacomments added exceeded the "
        "maximum length (%i) and have been truncated.  Reduce the number or size of "
        "uacomments to avoid truncation."),
    QT_TRANSLATE_NOOP("pyrrha",
        ""
        "Transaction has %d inputs and %d outputs. Maximum inputs allowed are %d and "
        "maximum outputs are %d"),
    QT_TRANSLATE_NOOP("pyrrha",
        ""
        "Transaction has %d inputs. Maximum inputs allowed is %d. Try reducing inputs "
        "by transferring a smaller amount."),
    QT_TRANSLATE_NOOP("pyrrha",
        ""
        "WARNING: abnormally high number of blocks generated, %d blocks received in "
        "the last %d hours (%d expected)"),
    QT_TRANSLATE_NOOP("pyrrha",
        ""
        "WARNING: check your network connection, %d blocks received in the last %d "
        "hours (%d expected)"),
    QT_TRANSLATE_NOOP("pyrrha",
        ""
        "Wallet is not password protected. Your funds may be at risk! Goto \"Settings"
        "\" and then select \"Encrypt Wallet\" to create a password."),
    QT_TRANSLATE_NOOP("pyrrha",
        ""
        "Warning: Could not open deployment configuration CSV file '%s' for reading"),
    QT_TRANSLATE_NOOP("pyrrha",
        ""
        "Warning: The network does not appear to fully agree! Some miners appear to "
        "be experiencing issues."),
    QT_TRANSLATE_NOOP("pyrrha",
        ""
        "Warning: Unknown block versions being mined! It's possible unknown rules are "
        "in effect"),
    QT_TRANSLATE_NOOP("pyrrha",
        ""
        "Warning: Wallet file corrupt, data salvaged! Original %s saved as %s in %s; "
        "if your balance or transactions are incorrect you should restore from a "
        "backup."),
    QT_TRANSLATE_NOOP("pyrrha",
        ""
        "Warning: We do not appear to fully agree with our peers! You may need to "
        "upgrade, or other nodes may need to upgrade."),
    QT_TRANSLATE_NOOP("pyrrha",
        ""
        "You are trying to use -wallet.auto but neither -spendzeroconfchange nor -"
        "wallet.instant is turned on"),
    QT_TRANSLATE_NOOP("pyrrha",
        ""
        "You are trying to use wallet.fallbackFee which has been deprecated an no "
        "longer in  use - use wallet.payTxFee instead "),
    QT_TRANSLATE_NOOP("pyrrha",
        ""
        "You are trying to use wallet.minTxFee which has been deprecated an no longer "
        "in  use - use wallet.payTxFee instead "),
    QT_TRANSLATE_NOOP("pyrrha",
        ""
        "You can not send free transactions if you have configured a -relay."
        "limitFreeRelay of zero"),
    QT_TRANSLATE_NOOP("pyrrha",
        ""
        "You need to rebuild the database using -reindex to go back to unpruned "
        "mode.  This will redownload the entire blockchain"),
    QT_TRANSLATE_NOOP("pyrrha", "%s "),
    QT_TRANSLATE_NOOP("pyrrha", "%s corrupt, salvage failed"),
    QT_TRANSLATE_NOOP("pyrrha", "-maxtxpool must be at least %d MB"),
    QT_TRANSLATE_NOOP("pyrrha", "-xthinbloomfiltersize must be at least %d Bytes"),
    QT_TRANSLATE_NOOP("pyrrha", "Activating best chain..."),
    QT_TRANSLATE_NOOP("pyrrha", "Cannot downgrade wallet"),
    QT_TRANSLATE_NOOP("pyrrha", "Cannot resolve -bind address: '%s'"),
    QT_TRANSLATE_NOOP("pyrrha", "Cannot resolve -externalip address: '%s'"),
    QT_TRANSLATE_NOOP("pyrrha", "Cannot resolve -whitebind address: '%s'"),
    QT_TRANSLATE_NOOP("pyrrha", "Cannot write default address"),
    QT_TRANSLATE_NOOP("pyrrha", "CommitTransaction failed."),
    QT_TRANSLATE_NOOP("pyrrha", "Copyright (C) 2015-%i The Bitcoin Unlimited Developers"),
    QT_TRANSLATE_NOOP("pyrrha", "Corrupted block database detected"),
    QT_TRANSLATE_NOOP("pyrrha", "Deployment configuration file '%s' not found"),
    QT_TRANSLATE_NOOP("pyrrha", "Do you want to rebuild the block database now?"),
    QT_TRANSLATE_NOOP("pyrrha", "Done loading"),
    QT_TRANSLATE_NOOP("pyrrha", "Error initializing block database"),
    QT_TRANSLATE_NOOP("pyrrha", "Error initializing wallet database environment %s!"),
    QT_TRANSLATE_NOOP("pyrrha", "Error loading %s"),
    QT_TRANSLATE_NOOP("pyrrha", "Error loading %s: Wallet corrupted"),
    QT_TRANSLATE_NOOP("pyrrha", "Error loading %s: Wallet requires newer version of %s"),
    QT_TRANSLATE_NOOP("pyrrha", "Error loading %s: You can't disable HD on a already existing HD wallet"),
    QT_TRANSLATE_NOOP("pyrrha", "Error opening block database"),
    QT_TRANSLATE_NOOP("pyrrha", "Error"),
    QT_TRANSLATE_NOOP("pyrrha", "Error: A fatal internal error occurred, see debug.log for details"),
    QT_TRANSLATE_NOOP("pyrrha", "Error: Disk space is low!"),
    QT_TRANSLATE_NOOP("pyrrha", "Failed to listen on any port. Use -listen=0 if you want this."),
    QT_TRANSLATE_NOOP("pyrrha", "Importing..."),
    QT_TRANSLATE_NOOP("pyrrha", "Incorrect or no genesis block found. Wrong datadir for network?"),
    QT_TRANSLATE_NOOP("pyrrha", "Information"),
    QT_TRANSLATE_NOOP("pyrrha", "Initialization sanity check failed. %s is shutting down."),
    QT_TRANSLATE_NOOP("pyrrha", "Insufficient funds or funds not confirmed"),
    QT_TRANSLATE_NOOP("pyrrha", "Invalid -onion address: '%s'"),
    QT_TRANSLATE_NOOP("pyrrha", "Invalid -proxy address: '%s'"),
    QT_TRANSLATE_NOOP("pyrrha", "Invalid netmask specified in -whitelist: '%s'"),
    QT_TRANSLATE_NOOP("pyrrha", "Keypool ran out, please call keypoolrefill first"),
    QT_TRANSLATE_NOOP("pyrrha", "Loading Orphanpool"),
    QT_TRANSLATE_NOOP("pyrrha", "Loading TxPool"),
    QT_TRANSLATE_NOOP("pyrrha", "Loading addresses..."),
    QT_TRANSLATE_NOOP("pyrrha", "Loading banlist..."),
    QT_TRANSLATE_NOOP("pyrrha", "Loading block index..."),
    QT_TRANSLATE_NOOP("pyrrha", "Loading wallet..."),
    QT_TRANSLATE_NOOP("pyrrha", "Need to specify a port with -whitebind: '%s'"),
    QT_TRANSLATE_NOOP("pyrrha", "Not enough file descriptors available."),
    QT_TRANSLATE_NOOP("pyrrha", "Opening Block database..."),
    QT_TRANSLATE_NOOP("pyrrha", "Opening Coins Cache database..."),
    QT_TRANSLATE_NOOP("pyrrha", "Opening UTXO database..."),
    QT_TRANSLATE_NOOP("pyrrha", "Portions Copyright (C) 2009-%i The Bitcoin Core Developers"),
    QT_TRANSLATE_NOOP("pyrrha", "Portions Copyright (C) 2014-%i The Bitcoin XT Developers"),
    QT_TRANSLATE_NOOP("pyrrha", "Prune cannot be configured with a negative value."),
    QT_TRANSLATE_NOOP("pyrrha", "Prune mode is incompatible with -txindex."),
    QT_TRANSLATE_NOOP("pyrrha", "Pruning blockstore..."),
    QT_TRANSLATE_NOOP("pyrrha", "Reaccepting Wallet Transactions"),
    QT_TRANSLATE_NOOP("pyrrha", "Rescanning..."),
    QT_TRANSLATE_NOOP("pyrrha", "Signing transaction failed"),
    QT_TRANSLATE_NOOP("pyrrha", "Starting txindex"),
    QT_TRANSLATE_NOOP("pyrrha", "The transaction amount is too small to pay the fee"),
    QT_TRANSLATE_NOOP("pyrrha", "This is experimental software."),
    QT_TRANSLATE_NOOP("pyrrha", "Transaction amount too small"),
    QT_TRANSLATE_NOOP("pyrrha", "Transaction amounts must be positive"),
    QT_TRANSLATE_NOOP("pyrrha", "Transaction has %d outputs. Maximum outputs allowed is %d"),
    QT_TRANSLATE_NOOP("pyrrha", "Transaction of %d bytes is too large. Maximum allowed is %d bytes"),
    QT_TRANSLATE_NOOP("pyrrha", "Transaction too large for fee policy"),
    QT_TRANSLATE_NOOP("pyrrha", "Turn off auto consolidate and try sending again."),
    QT_TRANSLATE_NOOP("pyrrha", "Unable to bind to %s on this computer (bind returned error %s)"),
    QT_TRANSLATE_NOOP("pyrrha", "Unable to bind to %s on this computer. %s is probably already running."),
    QT_TRANSLATE_NOOP("pyrrha", "Unable to start RPC services. See debug log for details."),
    QT_TRANSLATE_NOOP("pyrrha", "Unknown network specified in -onlynet: '%s'"),
    QT_TRANSLATE_NOOP("pyrrha", "Upgrading block database...This could take a while."),
    QT_TRANSLATE_NOOP("pyrrha", "Upgrading txindex database "),
    QT_TRANSLATE_NOOP("pyrrha", "Upgrading txindex database..."),
    QT_TRANSLATE_NOOP("pyrrha", "User Agent comment (%s) contains unsafe characters."),
    QT_TRANSLATE_NOOP("pyrrha", "Verifying blocks..."),
    QT_TRANSLATE_NOOP("pyrrha", "Verifying wallet..."),
    QT_TRANSLATE_NOOP("pyrrha", "Waiting for Genesis Block..."),
    QT_TRANSLATE_NOOP("pyrrha", "Wallet %s resides outside data directory %s"),
    QT_TRANSLATE_NOOP("pyrrha", "Wallet needed to be rewritten: restart %s to complete"),
    QT_TRANSLATE_NOOP("pyrrha", "Warning"),
};
