FROM ubuntu:20.04

RUN groupadd -r pyrrha && useradd -r -m -g pyrrha pyrrha

RUN set -ex \
	&& apt-get update \
	&& apt-get install -qq --no-install-recommends ca-certificates dirmngr gosu wget \
	&& rm -rf /var/lib/apt/lists/*

ENV PYRRHA_VERSION 1.1.0.0
ENV PYRRHA_URL https://bitcoinunlimited.info/pyrrha/1.1.0/pyrrha-1.1.0.0-linux64.tar.gz
ENV PYRRHA_SHA256 c6821e0e6be4c4519c92ef1e91ae8dea6a493e0d9f960b274a7fd0df75bc0332

# install pyrrha binaries
RUN set -ex \
	&& cd /tmp \
	&& wget -qO pyrrha.tar.gz "$PYRRHA_URL" \
	&& echo "$PYRRHA_SHA256 pyrrha.tar.gz" | sha256sum -c - \
	&& tar -xzvf pyrrha.tar.gz -C /usr/local --strip-components=1 --exclude=*-qt \
	&& rm -rf /tmp/*

# create data directory
ENV PYRRHA_DATA /data
RUN mkdir "$PYRRHA_DATA" \
	&& chown -R pyrrha:pyrrha "$PYRRHA_DATA" \
	&& ln -sfn "$PYRRHA_DATA" /home/pyrrha/.pyrrha \
	&& chown -h pyrrha:pyrrha /home/pyrrha/.pyrrha
VOLUME /data

COPY docker-entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

EXPOSE 7228 7227 7230 7229

CMD ["pyrrhad"]
