description "Pyrrha Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env PYRRHAD_BIN="/usr/bin/pyrrhad"
env PYRRHAD_USER="pyrrha"
env PYRRHAD_GROUP="pyrrha"
env PYRRHAD_PIDDIR="/var/run/pyrrhad"
# upstart can't handle variables constructed with other variables
env PYRRHAD_PIDFILE="/var/run/pyrrhad/pyrrhad.pid"
env PYRRHAD_CONFIGFILE="/etc/pyrrha/pyrrha.conf"
env PYRRHAD_DATADIR="/var/lib/pyrrhad"

expect fork

respawn
respawn limit 5 120
kill timeout 60

pre-start script
    # this will catch non-existent config files
    # pyrrhad will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$PYRRHAD_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run pyrrhad."
        echo "The setting must appear in $PYRRHAD_CONFIGFILE"
        echo
        echo "This password is security critical to securing wallets "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following"
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is also recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"Bitcoin Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$PYRRHAD_PIDDIR"
    chmod 0755 "$PYRRHAD_PIDDIR"
    chown $PYRRHAD_USER:$PYRRHAD_GROUP "$PYRRHAD_PIDDIR"
    chown $PYRRHAD_USER:$PYRRHAD_GROUP "$PYRRHAD_CONFIGFILE"
    chmod 0660 "$PYRRHAD_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$PYRRHAD_PIDFILE" \
    --chuid $PYRRHAD_USER:$PYRRHAD_GROUP \
    --exec "$PYRRHAD_BIN" \
    -- \
    -pid="$PYRRHAD_PIDFILE" \
    -conf="$PYRRHAD_CONFIGFILE" \
    -datadir="$PYRRHAD_DATADIR" \
    -disablewallet \
    -daemon

