#!/bin/bash
#
#  pyrrhad The Pyrrha server.
#
#
# chkconfig: 345 80 20
# description: pyrrhad
# processname: pyrrhad
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/pyrrhad, see below
if [ -f /etc/sysconfig/pyrrhad ]; then
        . /etc/sysconfig/pyrrhad
fi

RETVAL=0

prog=pyrrhad
# you can override the lockfile via PYRRHAD_LOCKFILE in /etc/sysconfig/pyrrhad
lockfile=${PYRRHAD_LOCKFILE-/var/lock/subsys/pyrrhad}

# pyrrhad defaults to /usr/bin/pyrrhad, override with PYRRHAD_BIN
pyrrhad=${PYRRHAD_BIN-/usr/bin/pyrrhad}

# pyrrhad opts default to -disablewallet, override with PYRRHAD_OPTS
pyrrhad_opts=${PYRRHAD_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $pyrrhad $pyrrhad_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
